package Actions;

public enum PhysicalActivityType {
    OUT_OF_REEDS,
    ON_PATH_IN_GOOD_MOOD,
    LEAN_OVER_THE_RIVER,
    STAND_ON_BRIDGE,
    COME_UP_TO_BRIDGE,
    BE_IN_RIVER,
    BE_NOT_IN_RIVER,
    FALL_IN_RIVER_ACCIDENTALY,
    FALL_IN_RIVER_ON_PURPOSE,
    OUT_OF_FOREST,
    STAY_ON_BRIDGE
}
